### ISSUE TITLE
Fix numbering when more than 8 tabs are open

### ISSUE THREAD

**Issue by narinluangrath** [narinluangrath/numbered-tabs#2]
According to Chrome's [documentation](https://support.google.com/chrome/answer/157179?hl=en), the `⌘ + 9` shortcut means the last tab and not tab number 9. So if you have 10 tabs open, hitting `⌘ + 9` will open tab 10. The number of the tabs should reflect this, so in this example:

- Tab 10 should be labeled 9. (instead of 10.)
- Tab 9 should have a placeholder `-.`

**Comment by gary02** [comment]
using some extension like 'surfingkey',  User can switch to tag 9 (and all >9 tag) with keystroke ‘9T’. So, maybe providing a option is better.
